### ISSUE TITLE
Correct Barcode tool error - networkx-related

### ISSUE THREAD

**Issue by thi-trinh** [galaxyproject/dunovo#15]
Hello,

I'm running a private instance of galaxy on AWS and have DuNovo 2.14 installed (same issue when using DuNovo 2.15). When running the correct barcodes tool on a valid "Make Families" output, it resulted in an error with the following log:

#
Fatal error: Exit code 1 ()
Info: ref_dir "refdir" not found. Creating..
families: /mnt/galaxy/files/000/dataset_338.dat
refdir:   refdir
format:   sam
outfile:  correct.sam
outbase:  correct.sam
reads processed: 42270
reads with at least one reported alignment: 42168 (99.76%)
reads that failed to align: 102 (0.24%)
Reported 81752 alignments to 1 output stream(s)
Success. Output located in "correct.sam".
Traceback (most recent call last):
  File "/mnt/galaxy/tools/dunovo/2.14/nick/dunovo/fa563fa9b330/correct.py", line 12, in 
    import networkx
  File "/mnt/galaxy/tools/networkx/1.10/iuc/package_networkx_1_10/e761775277c1/lib/python/networkx/__init__.py", line 68, in 
    import networkx.utils
  File "/mnt/galaxy/tools/networkx/1.10/iuc/package_networkx_1_10/e761775277c1/lib/python/networkx/utils/__init__.py", line 2, in 
    from networkx.utils.decorators import *
  File "/mnt/galaxy/tools/networkx/1.10/iuc/package_networkx_1_10/e761775277c1/lib/python/networkx/utils/decorators.py", line 7, in 
    from decorator import decorator
ImportError: No module named decorator
#

This tool works in the version 2.0.12 of du novo (which also requires networkx 1.10) but that package of du novo does not have some of the new tools I needed.

Any help on resolving this would be greatly appreciated.

Thanks

Thi

**Comment by thi-trinh** [comment]
This issue was resolved by disabling the installation of toolshed-managed repo/tools dependencies during the installation of DuNovo. The only dependencies left enabled are the ones managed by conda.

**Comment by NickSto** [comment]
Thanks for reporting, @thi-trinh. I'm re-opening this to track the issue when installing via toolshed, which is still supported in the code for now (probably deprecated in the future).
